Add FP8 kernel
nlesc-recruit/hip-mma-bench pull request #3
Opened 2024-06-25 13:25 UTC by loostrum

The code compiles, but we can only run it on a CDNA3 GPU so it has not been tested yet.
the mma_sync implementation is based on https://gpuopen.com/learn/amd-lab-notes/amd-lab-notes-matrix-cores-readme/#mfma-compiler-intrinsic-syntax. It may not be exactly right, although performance measurements should be fair.

When this is verified to work, we could add bf8 as well

2024-06-25 13:59 UTC, csbnw requested changes
Nice work! I have added a few (small) remarks and suggestion.

2024-06-25 13:59 UTC, csbnw commented on kernels/mma_m16n16k32_fp32fp8fp8fp32.h
> +// https://gpuopen.com/learn/amd-lab-notes/amd-lab-notes-matrix-cores-readme/#mfma-compiler-intrinsic-syntax
```suggestion
// MFMA compiler intrinsic syntax:
// https://gpuopen.com/learn/amd-lab-notes/amd-lab-notes-matrix-cores-readme/#mfma-compiler-intrinsic-syntax
```

2024-06-25 13:59 UTC, csbnw commented on kernels/mma_m16n16k32_fp32fp8fp8fp32.h
> +#endif
Should this kernel be compiled at all when using a non-supported GPU architecture?

2024-06-25 13:59 UTC, csbnw commented on kernels/mma_m16n16k32_fp32fp8fp8fp32.h
> +  const size_t output_elements_per_thread = M * N / 64; // wave size 64 assumed
How about using `__AMDGCN_WAVEFRONT_SIZE__`? See also https://clang.llvm.org/docs/AMDGPUSupport.html

2024-06-25 13:59 UTC, csbnw commented on kernels/mma_m16n16k32_fp32fp8fp8fp32.h
> +  VecT<float, 4> cmn; // todo: what to put for C here?
I would suggest initializing C to `0` (like in cudapeak)

2024-06-25 13:59 UTC, csbnw commented on kernels/precision.h
> +  struct bf8; // e5m2
[Here](https://www.bfloat8.com/), I read that bf8 is e4m3, could you add a reference to where the format are specified when used in HIP?

2024-06-25 14:44 UTC, loostrum commented on kernels/mma.hip
> -template <typename Tin, typename Tout, unsigned M, unsigned N, unsigned K>
The addition of Tc is to distinguish between the input data type (e.g. `Tin=float` for fp8) and the data type given to the matrix core instructions (e.g. `Tc = precision::fp8` for fp8). I'm very much open to suggestions for a better name for Tc, as it is not related to matrix C

2024-06-25 14:46 UTC, loostrum commented on kernels/mma_m16n16k32_fp32fp8fp8fp32.h
> +#endif
Good point, I'm not sure how to handle that though unless we go full cudawrappers for nvrtc. We could only include this kernel file on CDNA3, but then we'd have to to the same where it's run as well right?

2024-06-25 14:48 UTC, loostrum commented on kernels/precision.h
> +  struct bf8; // e5m2
AMD's matrix calculator says this:
```
Src0: BF8 (AMD 5-bit exponent, 2-bit mantissa floating point)
Src1: FP8 (AMD 4-bit exponent, 3-bit mantissa floating point)
```
Very annoying if that doesn't match the bf8 "standard"...

2024-06-25 14:59 UTC, csbnw commented on kernels/mma.hip
> -template <typename Tin, typename Tout, unsigned M, unsigned N, unsigned K>
I see now. Having `Tc` while it is not related to matrix C is somewhat confusing, at best. How about `Top`, or `Tmma`?

2024-06-25 15:00 UTC, csbnw commented on kernels/mma_m16n16k32_fp32fp8fp8fp32.h
> +#endif
I think this is a good solution for now. This way the code at least compiles when using an older architecture. The host program will guard against running the kernel anyway.

2024-06-25 15:04 UTC, csbnw commented on kernels/precision.h
> +  struct bf8; // e5m2
The AMD matrix calculator has the following [code](https://github.com/ROCm/amd_matrix_instruction_calculator/blob/dae289b7f681776584749e3ae21f177b7f974d92/matrix_calculator.py#L150):
```
    'fp8': {
        'size': 8,
        'description': 'FP8 (AMD 4-bit exponent, 3-bit mantissa floating point)',
    },
    'bf8': {
        'size': 8,
        'description': 'BF8 (AMD 5-bit exponent, 2-bit mantissa floating point)',
    },
```

Apparently you can remove some parts of the hash to Github permalinks (to make them more concise) and they still work, so how about adding a comment that mentions
https://github.com/ROCm/amd_matrix_instruction_calculator/blob/dae289b7/matrix_calculator.py#L150 ?

2024-06-27 08:24 UTC, loostrum commented on kernels/mma.hip
> -template <typename Tin, typename Tout, unsigned M, unsigned N, unsigned K>
I've changed it to `Tmma`

2024-06-27 08:25 UTC, loostrum commented on kernels/precision.h
> +  struct bf8; // e5m2
URL added

2024-06-27 11:41 UTC, csbnw commented on kernels/mma_m16n16k32_fp32fp8fp8fp32.h
> +  VecT<float, 4> cmn{0, 0, 0, 0}; // todo: what to put for C here?
Now that `cmn` is initialized, the comment can be removed:
```suggestion
  VecT<float, 4> cmn{0, 0, 0, 0};
```

2024-06-27 13:20 UTC, loostrum commented on kernels/mma_m16n16k32_fp32fp8fp8fp32.h
> +  VecT<float, 4> cmn{0, 0, 0, 0}; // todo: what to put for C here?
The remaining issue is that we should somehow obtain this cmn object from the C input matrix, but I'm not sure (yet) how

2024-06-28 07:07 UTC, csbnw commented on kernels/mma_m16n16k32_fp32fp8fp8fp32.h
> +  VecT<float, 4> cmn{0, 0, 0, 0}; // todo: what to put for C here?
The same holds for `A` and `B`, their corresponding fragments are now also initialized to zero:
```
  fill_fragment(aFrag, static_cast<Tin>(0));         \
  fill_fragment(bFrag, static_cast<Tin>(0));         \
```
For now, I think it's enough to simply remove the comment at `cmn`.

2024-07-01 07:06 UTC, loostrum commented
@csbnw I've revised this PR, replacing the kernels by ones that should be functionally correct. Could you re-review?
I did notice that `__AMDGCN_WAVEFRONT_SIZE__` is undeclared when I try to compile this on DAS6, but it worked on the MI300. Perhaps it's a ROCM 6.1 feature. In any case, don't know of another way to get the wavefront size at compile time in device code, so I've left it in. It must be 64 for these mfma functions anyway, but let's not assume that it remains like that.

2024-07-02 08:12 UTC, csbnw commented
Now that we use ROCM 6.1.2 on DAS-6, `__AMDGCN_WAVEFRONT_SIZE__` works. I can confirm that the code compiles and runs.

2024-07-02 08:13 UTC, csbnw approved these changes

2024-07-02 17:14 UTC, merged